### PR TITLE
Examples and minor fixes

### PR DESCRIPTION
**Pull request by alisaono**
Created 5 examples (World, USA, India, Japan, Saudi Arabia populations) in our website format.
- Data: Area name, code, population
- Options: Width(%), color range (high, low), scale (lin/log), zoom scale, zoom ID, tooltip (active, color), ID and Weight (fixed fields)
- See commits: 58e2a78, 19432e4

Also minor fixes that came up while creating the examples:
- Changed a Map prop colorRange (array) to two props colorRangeHigh and colorRangeLow (strings): 329e615, 64bcad6
- Fixed log scale bug: 329e615
- Put Map component inside Resize to make responsive: 910185c
- Adding a new rule where the first item in paths can contain correction (must be ID'd as "correction"): a16f93d
- Adding correction to the India paths: a16f93d

Samples (Wolrd, USA)
screen shot 2017-12-07 at 11 19 59 pm
screen shot 2017-12-07 at 11 20 08 pm

@sanjaypojo @AlmahaAlmalki

### CODE REVIEW

**Comment by alisaono** [comment]
Also I realized I flipped colorRangeHigh and colorRangeLow when I was trying to transition from colorRange... cfe2b62 for the fix.

**Comment by alisaono** [comment]
e7b93f8 for changing the prop name 'zoomIDKey' to 'zoomID'

**Comment by sanjaypojo** [comment]
@alisaono, let's merge this during the meeting, since it's a large set of changes!

**Review by sanjaypojo — APPROVED** [review]
This is awesome 💯

**Pull request merged**
